package MuseumGUI;

import static MuseumGUI.OracleConnection.res;
import javax.swing.JDialog;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import javax.swing.JPanel.*;
import java.awt.Dimension;
import java.awt.Dialog;
import javax.swing.JOptionPane;
import java.io.InputStream;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

import java.sql.*;
import java.sql.DriverManager;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;



public class MuseumDB extends javax.swing.JFrame implements TableModelListener {
    /** 
     * Creates new form MuseumDBGUI
     */
    
    public MuseumDB() {
        OracleConnection.connectToDatabase();
        initComponents();
        RecentUpdateTable.removeColumn(RecentUpdateTable.getColumnModel().getColumn(0));
        PopularTable.removeColumn(PopularTable.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        InsertCollectionDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        descripArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        AddItemButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        creatorField = new javax.swing.JTextField();
        materialField = new javax.swing.JTextField();
        Contributor = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        contributorTable = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@delphi.cs.csubak.edu:1521:dbs01PU").createEntityManager();
        llrpCollectionQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT L FROM LlrpCollection L");
        llrpCollectionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : llrpCollectionQuery.getResultList();
        llrpCollectionQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM LlrpCollection l");
        llrpCollectionList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : llrpCollectionQuery1.getResultList();
        llrpMaintenanceQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM LlrpMaintenance l");
        llrpMaintenanceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : llrpMaintenanceQuery.getResultList();
        llrpContributorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM LlrpContributor l");
        llrpContributorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : llrpContributorQuery.getResultList();
        MaintDialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        workerCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        maintReasonCombo = new javax.swing.JComboBox<>();
        addMaintRecordButton = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecentUpdateTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PopularTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ResultTable = new javax.swing.JTable();
        AddMaintButton = new javax.swing.JButton();
        maintTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        LoanHistoryPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        MaintHistPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        maintTable = new javax.swing.JTable();
        exhibitPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        exhibitTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        NewMenu = new javax.swing.JMenu();
        addItemMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addLoanMenu = new javax.swing.JMenuItem();
        addAcquisitionMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        addWorkerMenu = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ReportsMenu = new javax.swing.JMenu();
        dailyReportButton = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        locationReportButton = new javax.swing.JMenuItem();
        collectionReportButton = new javax.swing.JMenuItem();

        InsertCollectionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("New Collection Item");

        jLabel2.setText("Name:");

        jLabel3.setText("Description:");

        descripArea.setColumns(20);
        descripArea.setLineWrap(true);
        descripArea.setRows(5);

        jLabel4.setText("Year of Origin:");

        AddItemButton.setText("Add Item");
        AddItemButton.setToolTipText("");
        AddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Type:");

        jLabel10.setText("Creator:");

        jLabel11.setText("Material:");

        javax.swing.GroupLayout InsertCollectionDialogLayout = new javax.swing.GroupLayout(InsertCollectionDialog.getContentPane());
        InsertCollectionDialog.getContentPane().setLayout(InsertCollectionDialogLayout);
        InsertCollectionDialogLayout.setHorizontalGroup(
            InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertCollectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AddItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(InsertCollectionDialogLayout.createSequentialGroup()
                            .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addComponent(yearField)
                                .addComponent(typeField)
                                .addComponent(creatorField)
                                .addComponent(materialField)
                                .addComponent(descripArea, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InsertCollectionDialogLayout.setVerticalGroup(
            InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertCollectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descripArea, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(creatorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddItemButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contributor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contributorTable.setColumnSelectionAllowed(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, llrpContributorList, contributorTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${street1}"));
        columnBinding.setColumnName("Street");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${city}"));
        columnBinding.setColumnName("City");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${state}"));
        columnBinding.setColumnName("State");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${zip}"));
        columnBinding.setColumnName("Zip");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${organization}"));
        columnBinding.setColumnName("Organization");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        contributorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contributorTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(contributorTable);
        contributorTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Contributor ID:");

        jLabel7.setText("OR");

        jButton2.setText("Add New Contributor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Use Selected Contributor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContributorLayout = new javax.swing.GroupLayout(Contributor.getContentPane());
        Contributor.getContentPane().setLayout(ContributorLayout);
        ContributorLayout.setHorizontalGroup(
            ContributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(ContributorLayout.createSequentialGroup()
                .addGroup(ContributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContributorLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContributorLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        ContributorLayout.setVerticalGroup(
            ContributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContributorLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(ContributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("New Maintenance Record");

        jLabel13.setText("Worker:");

        workerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Reason:");

        maintReasonCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addMaintRecordButton.setText("Add Record");
        addMaintRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaintRecordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaintDialogLayout = new javax.swing.GroupLayout(MaintDialog.getContentPane());
        MaintDialog.getContentPane().setLayout(MaintDialogLayout);
        MaintDialogLayout.setHorizontalGroup(
            MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(MaintDialogLayout.createSequentialGroup()
                        .addGroup(MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workerCombo, 0, 175, Short.MAX_VALUE)
                            .addComponent(maintReasonCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaintDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMaintRecordButton)
                .addContainerGap())
        );
        MaintDialogLayout.setVerticalGroup(
            MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaintDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(maintReasonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMaintRecordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RecentUpdateTable.setModel(OracleConnection.getFurnitureItems());
        RecentUpdateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecentUpdateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RecentUpdateTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Furniture Items", jPanel2);

        PopularTable.setModel(OracleConnection.getCommonMaintItems());
        PopularTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopularTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(PopularTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Commonly Maintained Items", jPanel3);

        ResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ResultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ResultTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Search Results", jPanel4);

        AddMaintButton.setText("Add Maintenance");
        AddMaintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMaintButtonActionPerformed(evt);
            }
        });

        maintTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Item ID:");

        jLabel5.setText("Collection Search:");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
                searchTextFieldActionPerformed1(evt);
            }
        });

        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(loanTable);

        javax.swing.GroupLayout LoanHistoryPanelLayout = new javax.swing.GroupLayout(LoanHistoryPanel);
        LoanHistoryPanel.setLayout(LoanHistoryPanelLayout);
        LoanHistoryPanelLayout.setHorizontalGroup(
            LoanHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        LoanHistoryPanelLayout.setVerticalGroup(
            LoanHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Loan History", LoanHistoryPanel);

        maintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(maintTable);

        javax.swing.GroupLayout MaintHistPanelLayout = new javax.swing.GroupLayout(MaintHistPanel);
        MaintHistPanel.setLayout(MaintHistPanelLayout);
        MaintHistPanelLayout.setHorizontalGroup(
            MaintHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        MaintHistPanelLayout.setVerticalGroup(
            MaintHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintHistPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Maintenance History", MaintHistPanel);

        exhibitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(exhibitTable);

        javax.swing.GroupLayout exhibitPanelLayout = new javax.swing.GroupLayout(exhibitPanel);
        exhibitPanel.setLayout(exhibitPanelLayout);
        exhibitPanelLayout.setHorizontalGroup(
            exhibitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        exhibitPanelLayout.setVerticalGroup(
            exhibitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exhibitPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Exhibit History", exhibitPanel);

        NewMenu.setText("New");
        NewMenu.setToolTipText("");
        NewMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NewMenuMousePressed(evt);
            }
        });

        addItemMenu.setText("Collection Item");
        addItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemMenuActionPerformed(evt);
            }
        });
        NewMenu.add(addItemMenu);
        NewMenu.add(jSeparator1);

        addLoanMenu.setText("Loan");
        addLoanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanMenuActionPerformed(evt);
            }
        });
        NewMenu.add(addLoanMenu);

        addAcquisitionMenu.setText("Acquisition");
        addAcquisitionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAcquisitionMenuActionPerformed(evt);
            }
        });
        NewMenu.add(addAcquisitionMenu);
        NewMenu.add(jSeparator2);

        addWorkerMenu.setText("Worker");
        NewMenu.add(addWorkerMenu);

        jMenuBar1.add(NewMenu);

        EditMenu.setText("Edit");

        jMenu3.setText("Update");

        jMenuItem7.setText("Loan");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        EditMenu.add(jMenu3);

        jMenu4.setText("Delete");
        EditMenu.add(jMenu4);

        jMenuBar1.add(EditMenu);

        ReportsMenu.setText("Reports");

        dailyReportButton.setText("Daily Report");
        dailyReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReportButtonActionPerformed(evt);
            }
        });
        ReportsMenu.add(dailyReportButton);
        ReportsMenu.add(jSeparator3);

        locationReportButton.setText("Item Location Report");
        locationReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationReportButtonActionPerformed(evt);
            }
        });
        ReportsMenu.add(locationReportButton);

        collectionReportButton.setText("Collection Summary");
        collectionReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionReportButtonActionPerformed(evt);
            }
        });
        ReportsMenu.add(collectionReportButton);

        jMenuBar1.add(ReportsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddMaintButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMaintButton)
                    .addComponent(maintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMenuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMenuMousePressed

    private void addLoanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoanMenuActionPerformed
        // TODO add your handling code here:
        Contributor.setSize(700,400);
        Contributor.setLocationRelativeTo(this);
        Contributor.setVisible(true);
    }//GEN-LAST:event_addLoanMenuActionPerformed

    private void addAcquisitionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAcquisitionMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAcquisitionMenuActionPerformed

    private void AddMaintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMaintButtonActionPerformed
        // TODO add your handling code here:
        
        String id = maintTextField.getText();
        
        if (id.equals(""))
        {
            JOptionPane.showMessageDialog(null, "A catalog ID # is required to create a maintenance record.");
            
        } else {
            MaintDialog.setSize(700,400);
            MaintDialog.setLocationRelativeTo(this);
            MaintDialog.setVisible(true);
        }
    }//GEN-LAST:event_AddMaintButtonActionPerformed

    private void dailyReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReportButtonActionPerformed
        // TODO add your handling code here:
        //call Daily Report??
        //Path to your .jasper file in your package
        String reportName = "/Reports/DailyReport.jasper";
         
        //Get a stream to read the file
        InputStream is = getClass().getResourceAsStream(reportName);
         
        try {
        //Fill the report with parameter, connection and the stream reader     
            JasperPrint jp = JasperFillManager.fillReport(is, null, OracleConnection.connect);
         
         //Viewer for JasperReport
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_dailyReportButtonActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void collectionReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionReportButtonActionPerformed
        // TODO add your handling code here:
        //call CollectionReport
        //Path to your .jasper file in your package
        String reportName = "/Reports/CollectionReport.jasper";
         
        //Get a stream to read the file
        InputStream is = getClass().getResourceAsStream(reportName);
         
        try {
        //Fill the report with parameter, connection and the stream reader     
            JasperPrint jp = JasperFillManager.fillReport(is, null, OracleConnection.connect);
         
         //Viewer for JasperReport
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_collectionReportButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
        
        //1. run a sql statement similar to SELECT * FROM CS342.LLRP_COLLECTION
        //WHERE TYPES LIKE '%it%';
        //2. 
        //set jtabbedpane5
        String input = searchTextField.getText();
        System.out.println(input);
        PreparedStatement preparedStatement = null;
        String sql = "SELECT c.collectID, c.Name, c.Description, c.YearOfOrigin, c.Types, c.Creator, c.Material FROM LLRP_Collection c WHERE (c.name LIKE ? OR c.collectID LIKE ? or c.types LIKE ? or c.yearoforigin LIKE ? or c.description LIKE ? or c.creator LIKE ? or c.material LIKE ?)";
        Vector items = new Vector();
        Vector column = new Vector();

        try{
            preparedStatement = OracleConnection.connect.prepareStatement(sql);
            
            for(int i = 1; i < 8; i++){
                preparedStatement.setString(i, "%" + input + "%");
            }
            ResultSet rs = preparedStatement.executeQuery();
            while(rs.next()) {
                Vector temp = new Vector();
                for(int i=1; i < 8; i++) {
                    temp.addElement(rs.getString(i));
                }
                items.addElement(temp);
            }

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
        column.addElement("ID");
        column.addElement("Name");
        column.addElement("Description");
        column.addElement("Year of Origin");
        column.addElement("Type");
        column.addElement("Creator");
        column.addElement("Material");

        DefaultTableModel model = new DefaultTableModel(items, column){boolean[] canEdit = new boolean [] {
        false,false,false,false,false,false,false};

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }};

        ResultTable.setModel(model);
        ResultTable.removeColumn(ResultTable.getColumnModel().getColumn(0));
        jTabbedPane5.setSelectedIndex(2);
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void addItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemMenuActionPerformed
        // trigger Collection JDialog
        InsertCollectionDialog.setSize(400,550);
        InsertCollectionDialog.setLocationRelativeTo(this);
        InsertCollectionDialog.setVisible(true);                
    }//GEN-LAST:event_addItemMenuActionPerformed

    private void AddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String desc = descripArea.getText();
        String year = yearField.getText();
        String type = typeField.getText();
        String creator = creatorField.getText();
        String material = materialField.getText();
        
        OracleConnection.addItem(name, desc, year, type, creator, material);
                
        //close JDialog
        InsertCollectionDialog.dispose();
        
        RecentUpdateTable.setModel(OracleConnection.getFurnitureItems());
        PopularTable.setModel(OracleConnection.getCommonMaintItems());
    }//GEN-LAST:event_AddItemButtonActionPerformed

    private void searchTextFieldActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed1
        jTabbedPane5.setSelectedIndex(2);
    }//GEN-LAST:event_searchTextFieldActionPerformed1

    private void locationReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationReportButtonActionPerformed
        // TODO add your handling code here:
        //Path to your .jasper file in your package
        String reportName = "/Reports/OnDisplay.jasper";
         
        //Get a stream to read the file
        InputStream is = getClass().getResourceAsStream(reportName);
         
        try {
        //Fill the report with parameter, connection and the stream reader     
            JasperPrint jp = JasperFillManager.fillReport(is, null, OracleConnection.connect);
         
         //Viewer for JasperReport
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_locationReportButtonActionPerformed

    private void RecentUpdateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecentUpdateTableMouseClicked
        // TODO add your handling code here:
        int row = RecentUpdateTable.rowAtPoint(evt.getPoint());//get mouse-selected row
        Object value = RecentUpdateTable.getModel().getValueAt(row,0);
        String str = value.toString();
        int id = Integer.parseInt(str);
        
        System.out.println(str);
        String sql = "SELECT C.Name, to_char(M.StartDate,'MON-DD-YY'), to_char(M.EndDate,'MON-DD-YY'), L.Purpose, L.Location, R.Name, R.Organization FROM LLRP_COLLECTION C INNER JOIN LLRP_MAKES_A M ON C.COLLECTID = M.COLLECTID INNER JOIN LLRP_LOAN L ON M.LOANID = L.LOANID INNER JOIN LLRP_Recipient R ON L.RecipientID = R.RecipientID WHERE C.COLLECTID = ?";
        String sql2 = "SELECT c.NAME, m.procedures, to_char(p.StartDate,'MON-DD-YY'), to_char(p.EndDate,'MON-DD-YY'), w.fname || ' ' || w.lname AS Name FROM LLRP_COLLECTION c INNER JOIN LLRP_PERFORMED_ON p ON c.collectid = p.collectid INNER JOIN LLRP_MAINTENANCE m ON p.maintainID = m.maintainID INNER JOIN LLRP_DOES d ON d.maintainID = m.maintainID INNER JOIN LLRP_WORKER w ON w.SSN = d.SSN WHERE c.collectID = ?";
        String sql3 = "SELECT c.name, e.concept, e.startdate, e.enddate, d.location FROM LLRP_COLLECTION c INNER JOIN LLRP_DISPLAYED_IN d on c.collectid = d.collectid INNER JOIN LLRP_EXHIBITION e ON d.exhibitID = e.exhibitID WHERE c.collectid = ?";
     
        PreparedStatement ps = null;
        PreparedStatement ps2 = null;
        PreparedStatement ps3 = null;
        
        //get info using SQL related to selected item
        try{
            ps = OracleConnection.connect.prepareStatement(sql);
            ps.setInt(1,id);
            ps2 = OracleConnection.connect.prepareStatement(sql2);
            ps2.setInt(1,id);
            ps3 = OracleConnection.connect.prepareStatement(sql3);
            ps3.setInt(1,id);

        }
        catch (SQLException e){
        }
        
        loanTable.setModel(OracleConnection.getLoan(ps));
        maintTable.setModel(OracleConnection.getMaint(ps2));
        exhibitTable.setModel(OracleConnection.getExhibit(ps3));
        
        maintTextField.setText(str);
    }//GEN-LAST:event_RecentUpdateTableMouseClicked

    private void PopularTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopularTableMouseClicked
        // TODO add your handling code here:
        int row = PopularTable.rowAtPoint(evt.getPoint());//get mouse-selected row
        Object value = PopularTable.getModel().getValueAt(row,0);
        String str = value.toString();
        int id = Integer.parseInt(str);
        
        System.out.println(str);
        String sql = "SELECT C.Name, to_char(M.StartDate,'MON-DD-YY'), to_char(M.EndDate,'MON-DD-YY'), L.Purpose, L.Location, R.Name, R.Organization FROM LLRP_COLLECTION C INNER JOIN LLRP_MAKES_A M ON C.COLLECTID = M.COLLECTID INNER JOIN LLRP_LOAN L ON M.LOANID = L.LOANID INNER JOIN LLRP_Recipient R ON L.RecipientID = R.RecipientID WHERE C.COLLECTID = ?";
        String sql2 = "SELECT c.NAME, m.procedures, to_char(p.StartDate,'MON-DD-YY'), to_char(p.EndDate,'MON-DD-YY'), w.fname || ' ' || w.lname AS Name FROM LLRP_COLLECTION c INNER JOIN LLRP_PERFORMED_ON p ON c.collectid = p.collectid INNER JOIN LLRP_MAINTENANCE m ON p.maintainID = m.maintainID INNER JOIN LLRP_DOES d ON d.maintainID = m.maintainID INNER JOIN LLRP_WORKER w ON w.SSN = d.SSN WHERE c.collectID = ?";
        String sql3 = "SELECT c.name, e.concept, e.startdate, e.enddate, d.location FROM LLRP_COLLECTION c INNER JOIN LLRP_DISPLAYED_IN d on c.collectid = d.collectid INNER JOIN LLRP_EXHIBITION e ON d.exhibitID = e.exhibitID WHERE c.collectid = ?";
      
        PreparedStatement ps = null;
        PreparedStatement ps2 = null;
        PreparedStatement ps3 = null;
        
        //get info using SQL related to selected item
        try{
            ps = OracleConnection.connect.prepareStatement(sql);
            ps.setInt(1,id);
            ps2 = OracleConnection.connect.prepareStatement(sql2);
            ps2.setInt(1,id);
            ps3 = OracleConnection.connect.prepareStatement(sql3);
            ps3.setInt(1,id);

        }
        catch (SQLException e){
        }
        
        loanTable.setModel(OracleConnection.getLoan(ps));
        maintTable.setModel(OracleConnection.getMaint(ps2));
        exhibitTable.setModel(OracleConnection.getExhibit(ps3));
        
        maintTextField.setText(str);
    }//GEN-LAST:event_PopularTableMouseClicked

    private void ResultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultTableMouseClicked
        // TODO add your handling code here:
        int row = ResultTable.rowAtPoint(evt.getPoint());//get mouse-selected row
        Object value = ResultTable.getModel().getValueAt(row,0);
        String str = value.toString();
        int id = Integer.parseInt(str);
        
        System.out.println(str);
        String sql = "SELECT C.Name, to_char(M.StartDate,'MON-DD-YY'), to_char(M.EndDate,'MON-DD-YY'), L.Purpose, L.Location, R.Name, R.Organization FROM LLRP_COLLECTION C INNER JOIN LLRP_MAKES_A M ON C.COLLECTID = M.COLLECTID INNER JOIN LLRP_LOAN L ON M.LOANID = L.LOANID INNER JOIN LLRP_Recipient R ON L.RecipientID = R.RecipientID WHERE C.COLLECTID = ?";
        String sql2 = "SELECT c.NAME, m.procedures, to_char(p.StartDate,'MON-DD-YY'), to_char(p.EndDate,'MON-DD-YY'), w.fname || ' ' || w.lname AS Name FROM LLRP_COLLECTION c INNER JOIN LLRP_PERFORMED_ON p ON c.collectid = p.collectid INNER JOIN LLRP_MAINTENANCE m ON p.maintainID = m.maintainID INNER JOIN LLRP_DOES d ON d.maintainID = m.maintainID INNER JOIN LLRP_WORKER w ON w.SSN = d.SSN WHERE c.collectID = ?";
        String sql3 = "SELECT c.name, e.concept, e.startdate, e.enddate, d.location FROM LLRP_COLLECTION c INNER JOIN LLRP_DISPLAYED_IN d on c.collectid = d.collectid INNER JOIN LLRP_EXHIBITION e ON d.exhibitID = e.exhibitID WHERE c.collectid = ?";
        
        PreparedStatement ps = null;
        PreparedStatement ps2 = null;
        PreparedStatement ps3 = null;
        
        //get info using SQL related to selected item
        try{
            ps = OracleConnection.connect.prepareStatement(sql);
            ps.setInt(1,id);
            ps2 = OracleConnection.connect.prepareStatement(sql2);
            ps2.setInt(1,id);
            ps3 = OracleConnection.connect.prepareStatement(sql3);
            ps3.setInt(1,id);

        }
        catch (SQLException e){
        }
        
        loanTable.setModel(OracleConnection.getLoan(ps));
        maintTable.setModel(OracleConnection.getMaint(ps2));
        exhibitTable.setModel(OracleConnection.getExhibit(ps3));
        
        maintTextField.setText(str);
    }//GEN-LAST:event_ResultTableMouseClicked

    private void maintTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintTextFieldActionPerformed
        // TODO add your handling code here:
        
        //redundant with addMaintButton
    }//GEN-LAST:event_maintTextFieldActionPerformed

    private void contributorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contributorTableMouseClicked
        // TODO add your handling code here:
        int row = contributorTable.rowAtPoint(evt.getPoint());//get mouse-selected row
        Object value = contributorTable.getModel().getValueAt(row,0);
        String str = value.toString();
        int id = Integer.parseInt(str);
        
        System.out.println(str);
    }//GEN-LAST:event_contributorTableMouseClicked

    private void addMaintRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaintRecordButtonActionPerformed
        // TODO add your handling code here:
        
        /*
        String name = nameField.getText();
        String desc = descripArea.getText();
        String year = yearField.getText();
        String type = typeField.getText();
        String creator = creatorField.getText();
        String material = materialField.getText();
        
        RecentUpdateTable.setModel(OracleConnection.getFurnitureItems());
        PopularTable.setModel(OracleConnection.getCommonMaintItems());
        */
        
        OracleConnection.addMaint();
        
        //close JDialog
        MaintDialog.dispose();
    }//GEN-LAST:event_addMaintRecordButtonActionPerformed

    public void tableChanged(TableModelEvent e) {
    int row = e.getFirstRow();
    int column = e.getColumn();
    TableModel model = (TableModel)e.getSource();
    String columnName = model.getColumnName(column);
    Object data = model.getValueAt(row, column);

    // Do something with the data...
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuseumDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuseumDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuseumDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuseumDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuseumDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JButton AddMaintButton;
    private javax.swing.JDialog Contributor;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JDialog InsertCollectionDialog;
    private javax.swing.JPanel LoanHistoryPanel;
    private javax.swing.JDialog MaintDialog;
    private javax.swing.JPanel MaintHistPanel;
    private javax.swing.JMenu NewMenu;
    private javax.swing.JTable PopularTable;
    private javax.swing.JTable RecentUpdateTable;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JTable ResultTable;
    private javax.swing.JMenuItem addAcquisitionMenu;
    private javax.swing.JMenuItem addItemMenu;
    private javax.swing.JMenuItem addLoanMenu;
    private javax.swing.JButton addMaintRecordButton;
    private javax.swing.JMenuItem addWorkerMenu;
    private javax.swing.JMenuItem collectionReportButton;
    private javax.swing.JTable contributorTable;
    private javax.swing.JTextField creatorField;
    private javax.swing.JMenuItem dailyReportButton;
    private javax.swing.JTextArea descripArea;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel exhibitPanel;
    private javax.swing.JTable exhibitTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField4;
    private java.util.List<MuseumGUI.LlrpCollection> llrpCollectionList;
    private java.util.List<MuseumGUI.LlrpCollection> llrpCollectionList1;
    private javax.persistence.Query llrpCollectionQuery;
    private javax.persistence.Query llrpCollectionQuery1;
    private java.util.List<MuseumGUI.LlrpContributor> llrpContributorList;
    private javax.persistence.Query llrpContributorQuery;
    private java.util.List<MuseumGUI.LlrpMaintenance> llrpMaintenanceList;
    private javax.persistence.Query llrpMaintenanceQuery;
    private javax.swing.JTable loanTable;
    private javax.swing.JMenuItem locationReportButton;
    private javax.swing.JComboBox<String> maintReasonCombo;
    private javax.swing.JTable maintTable;
    private javax.swing.JTextField maintTextField;
    private javax.swing.JTextField materialField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField typeField;
    private javax.swing.JComboBox<String> workerCombo;
    private javax.swing.JTextField yearField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
